# test the rod scanning stuff
RS_SCALE_BY = 0;     
RS_SKIP_BRAGGS = TRUE;
RS_CHECK_SCAN = FALSE;
RS_PLOT_AVE = TRUE;

#RS_SAT_CNTR_IDX = 2
#RS_SAT_CNTR_VAL = 1e5

#RS_TEST = TRUE;
#FS_MOVE = FALSE;
#FS_WAIT = FALSE;

freeze 0 5 0
LAMBDA = 0.7
DET = 3;
MON = 0;
#test_scan  H  K  L_start  L_end  del_L   Scan_Axis   Max_count  L_bragg  Delta_Lbragg
#test_scan   1  1    0.3     2.2     0.01     keta        30         0         2
test_scan    1  1    0.3       1     0.2      keta         1         0         2
