fake_dscan keta -1 1 30 1 100 10 .3

sleep(.3)

array x[40][1]
array y[40][1]
array z[10]

x[0:NPTS-1] = SCAN_D[0:NPTS-1][0]
y[0:NPTS-1] = SCAN_D[0:NPTS-1][DET+1]/SCAN_D[0:NPTS-1][MON+1]

p x, y


def my_macro(x,y,n) '{
   local array m[1][4]    
    p m[0][0] = array_op("rows",x)
    p m[0][1] =  array_op("cols",x)

    p m[0][2] =  array_op("rows",y)
    p m[0][3] =  array_op("cols",y)

    
    array_plot(x[0:n-1],y[0:n-1])
    return(m)

}'